# محیط‌های رنگی

محیط‌های رنگی می تواند برای اطلاع رسانی یا هشدار دادن به خوانندگان در طول متن مفید باشد.
برای ایجاد این محیط‌ها، از بسته‌های لاتک 
`wesomebox` 
و 
`tcolorbox` 
و پیش‌فرض‌های آن استفاده می‌کنیم.


:::: {.rmdNote data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdnote data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdTip data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdtip data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdThink data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdthink data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdWarning data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdwarning data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdTodo data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

:::: {.rmdtodo data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
::::

## محیط‌های رنگی ریاضی‌نویسی

علاوه بر آن محیط‌های نوشتن گزاره‌های ریاضی هم قابل استفاده هستند.


::: {.Theorem data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Definition data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Lemma data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Corollary data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Proposition data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Exercise data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Example data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Remark data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Proof data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.Solution data-latex="{}{}"}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::


::: {.rmdexer data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::

::: {.rmdsol data-latex=""}
لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است.
:::
